[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/oldoxford"
  to = "https://app.hellosign.com/s/BhQr52dI"
  status = 302
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
